spring:
  application:
    name: idol

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: false
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
   secret: ${JWT_SECRET}
   expiration: 1800000 # 30분 (밀리초)
   refresh-expiration: 1209600000 # 14일 (밀리초)

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true       
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  paths-to-match:
    - /api/**
  packages-to-scan:
    - com.idol

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

cloud:
  aws:
    s3:
      bucket: ${BUCKET} # 버킷 이름
    stack.auto: false
    region.static: ${REGION} # 버킷 리전
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

